fix(ci): copy xkbcommon headers to bionic-libs instead of -I/usr/include
-I/usr/include caused conflicts with NDK sysroot:
  /usr/include/features-time64.h:20:10: fatal error: 'bits/wordsize.h'

Fix: Copy /usr/include/xkbcommon/* to bionic-libs/include/xkbcommon/
so -I$BIONIC_LIBS/include finds them without pulling in system headers.